name: Main - Build Dev Image and Push to Artifactory

# Controls when the workflow will run
on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_NAME: jag-adobe-common-service
  WORKING_DIRECTORY: .
  ENV_TAG: dev
  BRANCH_NAME: develop

jobs:
  build-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      
      - name: Get Release Version
        run: |
          branch=${GITHUB_REF##*/}
          version=$(echo $branch | cut -d "/" -f2-)
          echo "releaseVersion=$version" >> $GITHUB_ENV

      - name: Login to Artifactory
        uses: docker/login-action@v1
        with:
          registry: artifacts.developer.gov.bc.ca
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      
      # Get SHORT_SHA to tag images
      - name: Get short SHA
        id: short_sha
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "Short SHA: $SHORT_SHA"

      - name: Build Image
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          docker build -t artifacts.developer.gov.bc.ca/d735-adobe-common-service/${{env.IMAGE_NAME}}:${{env.ENV_TAG}} .
      
      - name: Docker Push to Artifactory
        run: |
          docker push artifacts.developer.gov.bc.ca/d735-adobe-common-service/${{env.IMAGE_NAME}}:${{env.ENV_TAG}}

      - name: Set GitOps SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.AC_SSH_KEY }}

      - name: Update Helm Values and Commit
        id: helm
        run: |
          
          # Commit and push the changes
          git config --global user.email "actions@github.com"
          git config --global user.name "Adobe Commons GitHub Actions"
          git clone -b ${{ env.BRANCH_NAME }} --single-branch git@github.com:bcgov-c/tenant-gitops-735b8b.git
          
          # Navigate to the directory containing your Helm values file for the environment develop -> DEV, test -> test
          cd tenant-gitops-735b8b/charts

          # Update the Helm values file with the new image tag and version
          DATETIME=$(date +'%Y-%m-%d %H:%M:%S')  # Get current date and time

          sed -i "s/acstag: .*/acstag: ${{ env.ENV_TAG }} # Image Updated on $DATETIME/" ../deploy/${{ env.ENV_TAG }}_values.yaml
          sed -i "s/acsversion: .*/acsversion: ${{ steps.short_sha.outputs.SHORT_SHA }} # Version Updated on $DATETIME/" ../deploy/${{ env.ENV_TAG }}_values.yaml
          
          git add .
          
          git add ../deploy/${{ env.ENV_TAG }}_values.yaml
          
          # Repackage Helm Chart      

          cd gitops

          helm dependency build
          
          cd charts

          git add .
          
          git commit -m "Update Adobe Commons image tag"
          git push origin ${{ env.BRANCH_NAME }} # Update the branch name as needed

      - name: Run Integration Tests
        env:
          TEST_STARTER_URL: ${{secrets.TEST_STARTER_URL}}
          BASIC_AUTH_USER: ${{ secrets.BASIC_AUTH_USER }}
          BASIC_AUTH_PASS: ${{ secrets.BASIC_AUTH_PASS }}
        run: |
          RET=`curl --write-out '%{content_type}' --output TestErrors.zip --request GET --user ${BASIC_AUTH_USER}:${BASIC_AUTH_PASS} --url ${TEST_STARTER_URL}`
          if [ "$RET" = "application/zip" ]; then
            echo "Status: Failed Integration Test(s) found!"
            exit 1
          fi
          if [ "$RET" = "application/json" ]; then
            echo "Status: All Tests Passed"
          fi
          if [ "$RET" != "application/zip" ] && [ "$RET" != "application/json" ]; then
            echo "Received content_type is $RET, was expecting application/json or application/zip"
            exit 1
          fi

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3.1.1
        if: failure()
        with:
          name: integration-tests-report
          path: |
            TestErrors.zip
          retention-days: 5
